

--- 
apiVersion: v1 
kind: Service 
metadata:
  name: fb-lb-svc 
  labels:
    name: facebook
    env: prod
    tier: frontend
spec:
  type: LoadBalancer
  selectors:
    app: facebook 
    env: prod
    tier: frontend
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
